version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-46-137-100-204.eu-west-1.compute.amazonaws.com
            database: d66j6fuut2nkb0
            user: kzquklvjvzingm
            password: 215486a384a8670fcebbdb7a5d5311bf833a17b242c3fe5ff757a6287f77ed94
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true